spring:
  application:
    name: medmanage-backend
  datasource:
    url: jdbc:mysql://sql.wsfdb.cn:3306/yukirinllmedmanage?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: YukiRinLLMedManage
    password: LUOCANYU
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: redis-15749.c52.us-east-1-4.ec2.cloud.redislabs.com
    port: 15749
    password: IDxlxgCOGp89HeXv4KBeZOmy4YE1nuqp
    database: 0

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  config: classpath:log4j2.xml

jwt:
  secret: medmanage_secret_key
  expiration: 86400000